config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get 'homes/about'

  get 'events/main'
  get 'events/genre'

  get 'users/joining_events'
  get 'users/my_events'

  get 'gloup/:id', to:'events#gloup', as:'gloup_events'
  get 'events/search'

  resources :events do
    resources :bulletin_boards, only: [:create, :destroy]
    resource :join_events
end

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

resources :users do
	get 'users/withdraw'
end

namespace :admins do
	resources :genres
	resources :users
  resources :events
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_many :events, dependent: :destroy
  validates :genre_name, presence: true

  attachment :genre_image
end

app/controllers/admins/genres_controller.rb
# frozen_string_literal: true

class Admins::GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  # GET /genres/new
  def new
    @genre = Genre.new
    @genres = Genre.where(is_valid: true)
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to admins_genres_path, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    genre=Genre.find(params[:id])
    if params[:genre][:is_vaild] == true
      genre.is_valid = true
      genre.update(genre_params)
      redirect_to admins_genres_path
     else
      genre.is_valid = false
      genre.update(genre_params)
      redirect_to admins_genres_path
     end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def genre_params
    params.require(:genre).permit(:genre_name, :is_valid, :genre_image)
  end
end

app/controllers/genres_controller.rb
# frozen_string_literal: true

class GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/new
  def new
    @genre = Genre.new
    @genres = Genre.where(is_valid: true)
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def genre_params
    params.require(:genre).permit(:genre_name, :is_valid, :genre_image)
  end
end

app/helpers/genres_helper.rb
# frozen_string_literal: true

module GenresHelper
end

app/views/admins/genres/_form.html.erb
<%= form_with model: genre, url: admins_genre_path, local: true do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :genre_name %>
    <%= form.text_field :genre_name %>
  </div>
  <div class="field">
    <%= form.attachment_field :genre_image %>
  </div>

  <div class="field">
    <%= form.radio_button :is_valid ,true %>
    <%= label_tag :is_valid, "有効" %>
    <%= form.radio_button :is_valid ,false %>
    <%= label_tag :is_vaild,"無効" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', admins_genre_path %> |
<%= link_to 'Back', admins_genres_path %>

app/views/admins/genres/index.html.erb
<div class="container">
  <h2>ジャンル追加・一覧画面</h2>
  <%= form_for(@genre,url:"/admins/genres") do |f| %>
  <b>ジャンル</b>
  <%= f.text_field :genre_name %>
  <%= f.radio_button :is_valid, true %>
  <%= label_tag :is_valid, "有効" %>
  <%= f.radio_button :is_valid, false %>
  <%= label_tag :is_vaild,"無効" %>
  <%= f.submit "追加",class:"btn btn-info" %>
  <% end %>
  <div class="row">
    <div class="col-xs-11">
      <table class="table table-bordered">
        <thead style="background-color: #d0e4e2;">
          <tr>
            <th>イメージ画像</th>
            <th>ジャンル</th>
            <th>状態</th>
            <th></th>
          </tr>
        </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= attachment_image_tag(genre, :genre_image, :fill, 150, 150, fallback: "no_image.jpg") %>
              </td>
              <td>
                <%= genre.genre_name %>
              </td>
              <td>
                <%if genre.is_valid==true %>
                  <p>有効</p>
                <% else %>
                  <p>無効</p>
                <%end%>
              </td>
            <td class="text-center">
              <%= link_to "編集する", edit_admins_genre_path(genre.id),class:"btn btn-primary" %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admins/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/admins/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Genre name:</strong>
  <%= @genre.genre_name %>
</p>

<p>
  <strong>Is valid:</strong>
  <%= @genre.is_valid %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>