config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get 'homes/about'

  get 'events/main'
  get 'events/genre'

  get 'users/joining_events'
  get 'users/my_events'

  get 'gloup/:id', to:'events#gloup', as:'gloup_events'
  get 'events/search'

  resources :events do
    resources :bulletin_boards, only: [:create, :destroy]
    resource :join_events
end

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

resources :users do
	get 'users/withdraw'
end

namespace :admins do
	resources :genres
	resources :users
  resources :events
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

class PostcodeValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A[0-9]{3}-[0-9]{4}\z/
      record.errors.add(attribute, 'は、数字3桁＋ハイフン（-）＋数字4桁の形式で入力してください。')
    end
  end
end

class DateValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    value = record.send("#{attribute}_before_type_cast")
    begin
      Date.parse value if value.present?
    rescue ArgumentError
      record.errors[attribute] << I18n.t('errors.messages.invalid')
    end
  end
end

class Event < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :join_events, dependent: :destroy
  has_many :bulletin_boards, dependent: :destroy

  enum sportst: { スポーツではない: 0, やや体を動かす: 1, 体を動かす: 2, 激しく体を動かす: 3 }

  validates :events_name, length: { in: 2..20 }, presence: true
  validates :entrance_fee, presence: true, format: { with: /\A[0-9０-９]+\z/, message: 'は全て数字で入力' }
  validates :persons, presence: true, format: { with: /\A[0-9０-９]+\z/, message: 'は全て数字で入力' }
  validates :event_status, presence: true
  validates :holding, presence: true, date: true
  validates :description, length: { in: 2..50 }, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/admins/events_controller.rb
# frozen_string_literal: true

class Admins::EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @bulletin_board = BulletinBoard.new
  end

  def edit
    # binding.pry
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update(event_params)
    redirect_to admins_event_path(event.id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:event_id, :user_id, :genre_id, :events_name, :entrance_fee, :sports, :persons, :event_image_id, :event_status, :description, :holding, :postcode, :prefecture_code, :address_city, :address_street, :address_building)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    if params[:id]
      @events = Event.where(genre_id: params[:id].to_i)
      @genre = Genre.find(params[:id])
    else
      @search = Event.ransack(params[:q])
      @events = @search.result
    end
    @genres = Genre.all
  end

  def genre
    @genres = Genre.where(is_valid: true )
  end

  def main
    @events = Event.page(params[:page]).reverse_order
    @genres = Genre.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @user = User.find(current_user.id)
    @bulletin_board = BulletinBoard.new
  end

  def gloup
    @event = Event.find(params[:id])
    @user = User.find(current_user.id)
    @bulletin_board = BulletinBoard.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  def search
    @search = Event.ransack(params[:q])
    @events = @search.result
  end

  # POST /events
  # POST /events.json
  def create
    user = User.find(current_user.id)
    @event = user.events.new(event_params)
    respond_to do |format|
      if @event.save
        @join_event = user.join_events.create(event_id: @event.id)
        format.html { redirect_to @event, notice: 'イベントを新しく立ち上げました。' }
        format.json { render :show, status: :created, location: @event }
      else
        # format.html { redirect_back(fallback_location: new_event_path)}
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'イベント情報を更新しました。' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_main_path, notice: 'イベントを消去しました。' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:event_id, :user_id, :genre_id, :events_name, :entrance_fee, :sports, :persons, :event_image_id, :event_status, :description, :holding, :postcode, :prefecture_code, :address_city, :address_street, :address_building)
  end
end

app/helpers/admin/event_helper.rb
# frozen_string_literal: true

module Admin::EventHelper
end

app/helpers/admins/events_helper.rb
# frozen_string_literal: true

module Admins::EventsHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>＜イベント詳細＞</h2>

  <div class="field ">
    <%= form.label :ジャンル %>
    <%= form.collection_select(:genre_id, Genre.where(is_valid: true), :id, :genre_name) %>
  </div>

  <div class="field">
    <h4>イベント名</h4>
    <%= form.text_field :events_name, :size=>"30",style: "border:double" %>
  </div>

  <div class="field">
    <h4>開催日</h4>
    <%= form.date_field :holding,style: "border:double" %>
  </div>

  <div class="field">
    <h4>参加費</h4>
    <%= form.text_field :entrance_fee,style: "border:double" %>
  </div>

  <div class="field field__margin">
    <h4>人数</h4>
    <%= form.number_field :persons,style: "border:double" %>
  </div>

  <div class="field field__margin">
    <h4>説明文</h4>
    <%= form.text_area :description, :size=>"60x5",style: "border:double" %>
  </div>

  <div class="field field__margin">
    <%= form.label :開催 %>
    <%= form.select :event_status,[["有効",true],["無効",false]] %>
  </div>

  <h2>＜開催地＞</h2>
  <h4>郵便番号</h4>
  <%= form.text_field :postcode,style: "border:double" %>
  <p>都道府県</p>
  <%= form.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :name, :name %>
  <p>市町村</p>
  <%= form.text_field :address_city,style: "border:double" %>
  <p>番地</p>
  <%= form.text_field :address_street,style: "border:double" %>
  <p>施設名</p>
  <%= form.text_field :address_building,style: "border:double" %>


  <div class="actions container event-actions__new">
    <%= form.submit"更新する" ,class:"btn btn-primary col-xs-10 col-xs-offset-1 sign_in" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/genre.html.erb
<h1>ジャンル検索</h1>

<div class="panel">
    <div class ="col-xs-12 ">
        <% @genres.each do |genre| %>
            <div class ="panel panel-warning col-responsive">
                <div class="panel-heading panel-warning">
                    <h3 class ="text-center" ><%= link_to genre.genre_name, events_path(id: genre.id) %></h3>
                </div>
                <div class="panel-body text-center ">
                    <%= attachment_image_tag genre, :genre_image, :fill, 270, 200, fallback: "no_image.jpg", :class => "resize" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/events/gloup.html.erb
<h2 style="font-size:60px;">掲示板</h2>

<div class="comment-destroy">
  <%= link_to 'イベントページに戻る', @event,class:"btn btn-primary btn-lg" %>
</div>
<div style="padding: 50px 10px 80px 10px;">
  <%= form_for @bulletin_board, url: event_bulletin_boards_path(@event), method: :post, remote: true do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "参加メンバーでの情報共有" %>
        </div>
    </div>
    <%= f.submit "送信する", class: "btn btn-default btn-lg btn-base-1 mt-20 pull-right"%>
  <% end %>
</div>
<div>
  <table id="js-table-bulletin_board" class="table" >
    <% @event.bulletin_boards.each do |bulletin_board| %>
          <%= render "bulletin_boards/comment",{bulletin_board:bulletin_board, user:@user, event:@event} %>
      <% end %>
  </table>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>イベント一覧</h1>
<h2>ジャンル：<%= @genre.genre_name %><%= link_to '新しくイベントを立ち上げる', new_event_path, class: " btn-success text-center btn-block new_event" %></h2>


<div class="container m-mainlist-main">
  <ul class = "m-mainlist-list">
  <% @events.each do |event| %>
    <li class="container m-mainlist__item">
      <div class="m-mainlist-item">
        <a>
          <span class="m-mainlist-item__ttl"><%= event.events_name %></span>
        </a>
        <p class="m-mainlist-item-event__period">
        <span class="m-mainlist-item-event__open">
          <% if event.event_status==true %>
                  開催予定
                  <% else %>
                  終了
                  <% end %>
        </span>
          開催日：<%= event.holding %>
        </p>
        <div class="m-mainlist-item__link">
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">主催者/<%= event.user.family_name %><%= event.user.first_name %></h3></p>
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">参加費/<%= event.entrance_fee %>円</h3></p>
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">参加人数/<%= event.persons %>中<%=event.join_events.length %>人参加</h3></p>
          <%= link_to '詳細', event,class:"btn btn-primary center-block" %>
        </div>

        <div class="m-mainlist-item__link">
          <h4 class="m-mainlist-item__txt"><%= event.description %></h4>
          <h3 class="m-mainlist-item-event__place"><h4 class="m-mainlist-item-event__placelink"><%= event.prefecture_code %></h4>
            <%= event.address_city %>
          </h3>
          <h3 class="m-mainlist-item-event__place"><h4 class="m-mainlist-item-event__placelink"><%= event.address_street %></h4></h3>
          <h3 class="m-mainlist-item-event__place"><h4 class="m-mainlist-item-event__placelink"><%= event.address_building %></h4></h3>
        </div>
        <a class="m-mainlist-item__img">
          <span><%= attachment_image_tag(@genre, :genre_image, :fill, 160, 160, fallback: "no_image.jpg") %></span>
        </a>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/events/main.html.erb
<div class="main-visual">
  <div class="main-visual-content">
    <p class="main-visual-text">
      shummit
    </p>
    <p class="main-visual-name main-visual-name__new">
      新しい趣味に
    </p>
    <p class="main-visual-name main-visual-name__my">
      新しい自分を見つける
    </p>
  </div>
</div>
<%= link_to '新しくイベントを立ち上げる', new_event_path, class: " btn-success text-center btn-block new_event" %>
<div class="containe"><h2>イベント一覧</h2></div>
<div class="container m-mainlist-main col-xs-12">
  <ul class = "m-mainlist-list">
  <% @events.each do |event| %>
    <li class="container m-mainlist__item">
      <div class="m-mainlist-item">
        <a>
          <span class="m-mainlist-item__ttl"><%= event.events_name %></span>
        </a>
        <p class="m-mainlist-item-event__period">
        <span class="m-mainlist-item-event__open">
          <% if event.event_status==true %>
                  開催予定
                  <% else %>
                  終了
                  <% end %>
        </span>
          開催日：<%= event.holding %>
        </p>
        <div class="m-mainlist-item__link">
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">主催者/<%= event.user.family_name %><%= event.user.first_name %></h3></p>
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">参加費/<%= event.entrance_fee %>円</h3></p>
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">参加人数/<%= event.persons %>中<%=event.join_events.length %>人参加</h3></p>
          <%= link_to '詳細', event,class:"btn btn-primary center-block" %>
        </div>

        <div class="m-mainlist-item__link">
          <p class="m-mainlist-item__map m-mainlist-item__map__text"><%= event.prefecture_code %>
            <%= event.address_city %>
          </p>
          <p class="m-mainlist-item__map m-mainlist-item__map__text"><%= event.address_street %></a>
          <p class="m-mainlist-item__map m-mainlist-item__map__text">ジャンル：<%= event.genre.genre_name %></p>
          <p class="m-mainlist-item__map m-mainlist-item__map__text"><%= event.description %></p>
        </div>
        <a class="m-mainlist-item__img">
          <span><%= attachment_image_tag(event.genre, :genre_image, :fill, 160, 160, fallback: "no_image.jpg") %></span>
        </a>
      </div>
    </li>
  <% end %>
  </ul>
</div>
    <%= paginate @events, class: "paginate" %>

app/views/events/new.html.erb
<h1 class="event-text__detail">〜イベント作成ページ〜</h1>
<div class="actions">
    <%= link_to '戻る', events_main_path,class:"btn btn-primary pull-right btn-lg" %>
</div>
<%= render 'form', event: @event %>

app/views/events/search.html.erb
<p id="notice"><%= notice %></p>

<h1>イベント一覧</h1>

<div class="container m-mainlist-main">
  <ul class = "m-mainlist-list">
  <% @events.each do |event| %>
    <li class="container m-mainlist__item">
      <div class="m-mainlist-item">
        <a>
          <span class="m-mainlist-item__ttl"><%= event.events_name %></span>
        </a>
        <p class="m-mainlist-item-event__period">
        <span class="m-mainlist-item-event__open">
          <% if event.event_status==true %>
                  開催予定
                  <% else %>
                  終了
                  <% end %>
        </span>
          開催日：<%= event.holding %>
        </p>
        <div class="m-mainlist-item__link">
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">主催者/<%= event.user.family_name %><%= event.user.first_name %></h3></p>
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">参加費/<%= event.entrance_fee %>円</h3></p>
          <p class="m-mainlist-item-event__place"><h3 class="m-mainlist-item-event__placelink">参加人数/<%= event.persons %>中<%=event.join_events.length %>人参加</h3></p>
          <%= link_to '詳細', event,class:"btn btn-primary center-block" %>
        </div>

        <div class="m-mainlist-item__link">
          <h4 class="m-mainlist-item__txt"><%= event.description %></h4>
          <h3 class="m-mainlist-item-event__place"><h4 class="m-mainlist-item-event__placelink"><%= event.prefecture_code %></h4>
            <%= event.address_city %>
          </h3>
          <h3 class="m-mainlist-item-event__place"><h4 class="m-mainlist-item-event__placelink"><%= event.address_street %></h4></h3>
          <h3 class="m-mainlist-item-event__place"><h4 class="m-mainlist-item-event__placelink"><%= event.address_building %></h4></h3>
        </div>
        <a class="m-mainlist-item__img">
          <span><%= attachment_image_tag(event.genre, :genre_image, :fill, 160, 160, fallback: "no_image.jpg") %></span>
        </a>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/events/show.html.erb
<h4 id="notice"><%= notice %></h4>
<table class="table table-bordered" >
      <thead>
        <tr>
          <h3 class="text-center" >イベント詳細</h3>
        </tr>
      </thead>
      <tbody>
          <tr class="my_text" >
              <th class="text-center success">
                <h3>主催者</h3>
              </th>
              <th class="text-center">
                <h3><%= @event.user.family_name %><%= @event.user.first_name %></h3>
              </th>
          </tr>
          <tr class="my_text ">
              <th class="text-center success">
                <h3>ジャンル</h3>
              </th>
              <th class="text-center">
                <h3><%= @event.genre.genre_name %></h3>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
                <h3>イベント名</h3>
              </th>
              <th class="text-center">
                <h3><%= @event.events_name %></h3>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
                <h3>参加費</h3>
              </th>
              <th class="text-center">
                <h3><%= @event.entrance_fee %>円</h3>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
                <h3>参加人数</h3>
              </th>
              <th class="text-center">
                <h3><%= @event.persons %>人/<%= @event.join_events.length %>人参加中</h3>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
                <h3>イベントステータス</h3>
              </th>
              <th class="text-center">
                <% if @event.event_status==true %>
                  <h3>開催中</h3>
                  <% else %>
                  <h3>終了</h3>
                  <% end %>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
                <h3>説明文</h3>
              </th>
              <th class="text-center my_text">
                <h3><%= @event.description %></h3>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
               <h3>開催日</h3>
              </th>
              <th class="text-center my_text">
                <h3><%= @event.holding %></h3>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
               <h3>開催地</h3>
              </th>
              <th class="text-center my_text">
                <h3 id="map-address"><%= @event.prefecture_code %><%= @event.address_city %><%= @event.address_street %></h3>
              </th>
          </tr>
          <tr class="my_text">
              <th class="text-center success">
               <h3>施設名</h3>
              </th>
              <th class="text-center">
                <h3 id="map-address"><%= @event.address_building %></h3>
              </th>
          </tr>
      </tbody>
</table>

<div class="event__map" id="map"></div>
<div class="t-event__map">
  <table class="table table-bordered" >
    <thead>
      <tr>
        <h3 class="text-center" >イベント開催地マップ</h3>
      </tr>
    </thead>
    <tbody>
        <tr class="my_text">
            <th class="text-center success">
             <h3>開催地</h3>
            </th>
            <th class="text-center my_text">
              <h3 id="map-address"><%= @event.prefecture_code %><%= @event.address_city %><%= @event.address_street %></h3>
            </th>
        </tr>
        <tr class="my_text">
            <th class="text-center success">
             <h3>施設名</h3>
            </th>
            <th class="text-center">
              <h3 id="map-address"><%= @event.address_building %></h3>
            </th>
        </tr>
    </tbody>
  </table>
</div>
<script>
function initMap() {

  var target = document.getElementById('map'); //マップを表示する要素を指定
  var address = '<%= @event.prefecture_code %><%= @event.address_city %><%= @event.address_street %>'; //住所を指定
  var geocoder = new google.maps.Geocoder();

  geocoder.geocode({ address: address }, function(results, status){
    if (status === 'OK' && results[0]){

      console.log(results[0].geometry.location);

       var map = new google.maps.Map(target, {
         center: results[0].geometry.location,
         zoom: 18
       });
       console.log('aaa')
       var marker = new google.maps.Marker({
         position: results[0].geometry.location,
         map: map,
         animation: google.maps.Animation.DROP
       });
       console.log(map)

    }else{
      //住所が存在しない場合の処理
      alert('住所が正しくないか存在しません。');
      target.style.display='none';
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY']%>=initMap" asynx defer></script>
<% if @event.join_events.where(user_id: current_user.id).exists? %>
  <table class="table table-bordered ">
      <thead>
        <tr>
          <h3 class="text-center">イベント参加者</h3>
        </tr>
      </thead>
      <thead>
        <tr class="success my_text">
          <th>
            <h4 class="text-center">アイコン</h4>
          </th>
          <th>
            <h4 class="text-center">名前</h4>
          </th>
          <th>
            <h4 class="text-center">アドレス</h4>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @event.join_events.each do |join_event| %>
          <tr class="my_text">
              <th class="text-center col-md-2">
                <%= attachment_image_tag(join_event.user, :profile_image, :fill, 62, 62, fallback: "no_image.jpg") %>
              <th class="text-center col-md-5">
                <h3><%= join_event.user.family_name %><%= join_event.user.first_name %></h3>
              </th>
              <th class="text-center col-md-5">
                <h3><%= join_event.user.email %></h3>
              </th>
          </tr>
          <% end %>
      </tbody>
  </table>

  <% if @event.user.id == current_user.id %>
  <% else %>
    <%= link_to '掲示板へ行く', gloup_events_path(@event.id),class: " btn btn-default btn-lg pull-left ", :style=>"margin:40px;" %>
    <%= link_to "イベントを抜ける", event_join_events_path(@event), method: :delete,class: "btn btn-danger btn-lg btn-margin", :style=>"margin:40px;", "data-confirm" => "本当にイベントを抜けますか" %>
  <% end %>
<% else %>
  <%  if @event.join_events.length < @event.persons %>
  <%= link_to "イベントに参加する", event_join_events_path(@event), method: :post,class: "btn btn-primary btn-lg pull-left btn-margin", :style=>"margin:40px;" %>

  <% else %>
    <h3>参加者がいっぱいです</h3>
  <% end %>

<% end %>

<% if @event.user.id == current_user.id %>
  <%= link_to '掲示板へ行く', gloup_events_path(@event.id),class: " btn btn-default btn-lg pull-left ", :style=>"margin:40px;" %>
  <%= link_to 'イベントを編集する', edit_event_path(@event),class: "btn btn-success btn-lg btn-margin", :style=>"margin:40px;" %>
  <%= link_to "イベントを削除する", event_path(@event), method: :delete,class: "btn btn-danger btn-lg pull-right", "data-confirm" => "本当に削除しますか？", :style=>"margin:40px;" %><br></h2>
<% else %>
<% end %>