config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get 'homes/about'

  get 'events/main'
  get 'events/genre'

  get 'users/joining_events'
  get 'users/my_events'

  get 'gloup/:id', to:'events#gloup', as:'gloup_events'
  get 'events/search'

  resources :events do
    resources :bulletin_boards, only: [:create, :destroy]
    resource :join_events
end

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

resources :users do
	get 'users/withdraw'
end

namespace :admins do
	resources :genres
	resources :users
  resources :events
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shummit</title>
    <%= favicon_link_tag('rogo.jpg') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css" >
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta charset="utf-8">
  </head>
  <body>
    <nav class="navbar navbar-fixed-top navbar-dark" role="navigation">
      <div class="container" >
        <div class="navbar-header">
          <a class="navbar-brand " href="/" ><%= image_tag 'rogo.jpg', size: '50x50' %></a>
          <a class="navbar-brand navbar-brand__font " href="/">Shummit</a>
          <% if admin_signed_in? || user_signed_in? %>
            <div class="pull-left" style="margin-top: 30px;">
              <%= search_form_for @search, url: "/events/search" do |f| %>
                  <%= f.text_field :prefecture_code_or_address_city_or_events_name_or_description_or_holding_cont, :size=>"23x5", placeholder: 'イベントを入力してください' %>
                  <%= f.submit ("検索") %>
              <% end %>
            </div>
          <% else %>
          <% end %>
          <button type="button" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <div id="sp-menu">
          <h2>MENU</h2>
          <% if admin_signed_in? %>
          <ul>
            <li><%= link_to (destroy_admin_session_path), method: :delete do %> <span class="glyphicon glyphicon-log-out logout head_item"></span> ログアウト <% end %></li>
            <li><%= link_to "会員一覧", admins_users_path,class:"glyphicon glyphicon-cart cart head_item" %></li>
            <li><%= link_to "ジャンル一覧", admins_genres_path,class:"glyphicon glyphicon-cart cart" %></li>
            <li><%= link_to "イベント一覧", admins_events_path,class:"glyphicon glyphicon-cart cart head_item" %></li>
          </ul>
          <% elsif user_signed_in? %>
          <ul>
            <li><%= link_to (destroy_user_session_path), method: :delete do %><span class="glyphicon glyphicon-log-out logout "></span> ログアウト <% end %></li>
            <li><%= link_to (events_main_path) do %><span class="glyphicon glyphicon-home home" aria-hidden="ture"></span>メインページ<% end %></li>
            <li><%= link_to " マイページ", user_path(current_user),class:"glyphicon glyphicon-log-in login" %></li>
            <li><%= link_to " ジャンル一覧", events_genre_path(current_user),class:"glyphicon glyphicon-log-in login" %></li>
          </ul>
          <% else %>
          <ul>
            <li><%= link_to " 新規登録", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
            <li><%= link_to " ログイン", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
            <li><%= link_to " About", homes_about_path, class: "glyphicon glyphicon-log-in" %></li>
            <li><%= link_to " 管理者", new_admin_session_path, class:"glyphicon glyphicon-edit head_item" %></li>
          </ul>
          <% end %>
        </div>
        <div id="hm-icon">
          <a class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>
          </button>
        </div>
        <div class="pull-right" >
          <!-- <header class="navbar navbar-fixed-top navbar-inverse"> -->
          <ul d="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">

          <!-- サインインしている場合の表示 -->
            <% if admin_signed_in? %>
              <li class="" >
                <h2  style="padding-top: 10px;">Admin画面</h2>
              </li>

              <li class="" >
                <%= link_to (destroy_admin_session_path), method: :delete do %> <span class="glyphicon glyphicon-log-out logout head_item"></span> ログアウト <% end %>
              </li>
              <li class="">
                <%= link_to "会員一覧", admins_users_path,class:"glyphicon glyphicon-cart cart head_item" %>
              </li>
              <li class="">
                <%= link_to "ジャンル一覧", admins_genres_path,class:"glyphicon glyphicon-cart cart" %>
              </li>
              <li class="">
                <%= link_to "イベント一覧", admins_events_path,class:"glyphicon glyphicon-cart cart head_item" %>
              </li>
             <% elsif user_signed_in? %>
             <!-- logoutを表示 -->
              <li class="center">
                <%= link_to (destroy_user_session_path), method: :delete do %><span class="glyphicon glyphicon-log-out logout "></span> ログアウト <% end %>
              </li>
              <li>
                <%= link_to (events_main_path) do %><span class="glyphicon glyphicon-home home" aria-hidden="ture"></span> メインページ<% end %>
              </li>
              <li class="">
                <%= link_to " マイページ", user_path(current_user),class:"glyphicon glyphicon-log-in login" %>
              </li>
              <li class="">
                <%= link_to " ジャンル一覧", events_genre_path(current_user),class:"glyphicon glyphicon-log-in login" %>
              </li>
              <% else %>
              <!-- sign upを表示 -->
              <li class="">
                <%= link_to " 新規登録", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
              </li>
              <!-- loginを表示 -->
              <li class="">
                <%= link_to " ログイン", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
              </li>
              <li class="">
                <%= link_to " About", homes_about_path, class: "glyphicon glyphicon-log-in" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container container-app">
    <%= yield %>
    </div>
    <footer class="footer pull-left text-right">
      <div class="container text-right">
          <p class="text-muted text-right">Copyright (C) 2020　Shummit</p>
      </div>
    </footer>
  <% if flash.any? %>
    <script type="text/javascript">
      <% flash.each do |key, value| %>
        <% key = "success" if key == "notice" %>
        <% key = "error" if key == "alert" %>
        toastr['<%= key %>']('<%= value %>');
      <% end %>
    </script>
  <% end %>
  </body>
</html>
<script>
  $(function() {

  $('.menu-trigger').on('click', function() {
    $(this).toggleClass('active');
    $('#sp-menu').fadeToggle();
    return false;
  });

 });
</script>